name: tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Configure Module Autoloading
        run: |
          # Create a temporary composer.json file for module autoloading
          echo '{
            "autoload": {
              "psr-4": {
                "Modules\\": "Modules/"
              }
            }
          }' > composer-temp.json
          
          # Use the temporary composer.json to dump autoload
          composer dump-autoload -o --no-dev --classmap-authoritative --ignore-platform-reqs --no-interaction --working-dir=composer-temp.json

      - name: Dump Autoload Modules
        run: |
          # Remove the temporary composer.json file
          rm composer-temp.json
          php artisan modules:update-autoloading

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Register Inertia Pages to ModulePageResolver
        run: npm run modules:register

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest
