name: tests

on:
  push:
    branches:
      - develop
      - main
      - test
  pull_request:
    branches:
      - develop
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Node Dependencies
        run: npm ci

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader


      - name: Copy Environment File
        run: cp .env.example .env

      - name: Configure Test Environment
        run: |
          echo "SESSION_DRIVER=file" >> .env
          echo "SESSION_PATH=/tmp/laravel-sessions" >> .env
          mkdir -p /tmp/laravel-sessions
          chmod 777 /tmp/laravel-sessions

      - name: Create Database Directory
        run: mkdir -p database

      - name: Create Database File
        run: touch database/database.sqlite

      - name: Set Session Storage Permissions
        run: |
          mkdir -p storage/framework/sessions
          chmod -R 777 storage/framework/sessions

      - name: Run Database Migrations
        run: php artisan migrate --seed --force

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Publish Ziggy Configuration
        run: php artisan ziggy:generate

      - name: Register Inertia Pages to ModulePageResolver
        run: npm run modules:register

      - name: Build Assets
        run: npm run build

      - name: Tests
        run: ./vendor/bin/pest
